### ISSUE TITLE
xarray integrations

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/DeltaMetrics#75]
a working list of integrations

- [x] along section coordinates in plotting `section.show()` [#77]
- [x] as in #34, need to decide how to specify the input to section locations (`y_idx=` for old behavior?) [#80]
- [x] `aerial_view` and `overlay_sparse_array` need to use coordinates from the planform object passed to them
- [x] calculations for channel width and depth [#77]
- [x] calculations for migration (time coordinate integration) [#92]

**Comment by elbeejay** [comment]
Note on tracking of time for the Mask objects: implementation of static methods (via @ decorators) **does not accurately track time**, however mask initialization via `__init__` **does accurately track time**. 

- [ ] correct / check time coordinate across all mask pathways
